### ISSUE TITLE
Reinstallation doesn't work

### ISSUE THREAD

**Issue by jabl** [CSCfi/ansible-role-pxe_bootstrap#3]
Reinstalling a node (with fgci-ansible:/tools/reinstall_node.yml) doesn't work. Adding some debugging output to boot.py shows:

<pre><code>
# curl http://10.10.254.20/cgi-bin/boot.py
[Errno 13] Permission denied: '/var/www/provision/reinstall/pe67'
apache
#!ipxe
exit
</code></pre>

(so what I added was to print the exception message, and the user the cgi script was running as). Unix permissions are alright, however I thing I noticed:

<pre><code>
[root@install2 ~]# sestatus 
SELinux status:                 enabled
</code></pre>

which I guess is what prevents the cgi script from deleting the reinstall file. Is this intentional, or should we disable selinux, or should it be fixed in some other way?

**Comment by martbhell** [comment]
The things we assume before ansible is in the kickstart: https://github.com/CSC-IT-Center-for-Science/fgci-ansible/blob/master/roles/provision_vm/templates/kickstart.cfg

Yes, selinux should be disabled. We could however quite easily add a role to configure selinux with ansible too. Just to be on the safe side. Another would be to set the appropriate selinux booleans or policies.

**Comment by jabl** [comment]
Ah, alright then. Must be due to some leftover of our unusual way of provisioning the install node. Closing.
