### ISSUE TITLE
Improve error logging messages in boot.py

### ISSUE THREAD

**Issue by martbhell** [CSCfi/ansible-role-pxe_bootstrap#8]
If the host name that the node was requesting was not found in the pxe_nodes.json file then boot.py just writes the hostname to syslog. Would be nice with something more descriptive.

<pre>
Jul  7 15:04:35 io-install boot.py: 'io'
</pre>

**Comment by A1ve5** [comment]
Soon it will be:
Sep 21 11:09:32 io-install.fgci.csc.fi boot.py[1585]: 'io4' hostname wasn't found in /var/www/provision/nodes/pxe_nodes.json
